### ISSUE TITLE
ICU4J lines in https://unicode-org.github.io/conformance/ all are labeled "74.2 74" regardless of ICU version

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#268] opened 2024-08-08 23:04 UTC
The labels to the left of each status bar in the chart for ICU4J should indicate the actual ICU version tested.

**Comment by sffc** [comment] 2024-08-19 22:51
Duplicate of #271

**Closed** 2024-08-19 22:51 UTC
